### ISSUE TITLE
Do not abort from a library

### ISSUE THREAD

**Issue by trapzero** [sustrik/libmill#81] opened 2015-08-03 20:25 UTC
I recommend never calling 'abort' or 'exit' from within library code, unless it is built in a Debug mode for testing.  

https://github.com/sustrik/libmill/blob/master/utils.h#L74  is called from:
https://github.com/sustrik/libmill/blob/master/valbuf.c#L47

You undermine the behavior of programs using your library.  Some programs may be running in critical or sensitive contexts and need to do some level of cleanup before exiting.  

You should return an error instead and let the calling code handle that.

**Comment by sustrik** [comment] 2015-08-03 20:40
assert() is used to catch bugs in the library -- the idea is that it's better to kill the process than let it continue running with undefined behaviour.

Memory allocation failures, though, are a different matter. They are not bugs, but there's no easy way to handle them, especially with respect to memory overcommit done by the operating system. The best way to deal with the problem is to limit the program itself (say specify the max number of concurrent connections) and provision the hardware accordingly.

**Comment by trapzero** [comment] 2015-08-03 21:37
Libraries shouldn't impose restrictions on the caller, at least not w/o explicitly stating the assumptions.  Most developers assume that any given library will not call abort() or exit() in any situation.  They would expect errors to be returned.  Some global var in your library could indicate that any call should return error after an unexpected event occurs.

It's also worth noting that overcommit is not defined as part of the behavior of realloc.  If overcommit is on (default on linux), realloc will never fail.

**Comment by sustrik** [comment] 2015-08-03 21:51
Exactly. You'll be killed by OOM later on. How is that different from exiting?

Anyway, you are right that the behviour should be documented.

**Comment by nirs** [comment] 2015-08-03 23:15
I agree that abort and asserts should be avoided in release builds. All errors should be communicated to the caller using return value/errno. The code should be correct if all asserts are removed.

**Comment by sustrik** [comment] 2015-08-04 04:55
In the case of violated assumptions, no. My life is too short to spend it debugging undefined behaviour.

As for the memory allocation failures, it's more tricky. One one hand, someone still has to show me a userland application than handles memory backpressure decently. On the other hand, it may be that I haven't been in the right place at the right time to see it. Theoretically, I can imagine a system that runs as a single application directly on the bare metal and handles all the memory management itself without having to worry about what other applications or the OS do at the moment. Space probe software, maybe? IoT kind of thingies? This may also be the case with unikernels, but I guess nobody has enough experience in that field yet to tell for sure.

Anyway, the use cases sound very exotic to me. What about adding a compile time switch to enable OOM reporting?

**Comment by sustrik** [comment] 2015-08-04 04:59
There are several assert in the network libraries that have to be replaced by error codes. Let's do that.

**Comment by sustrik** [comment] 2015-08-04 06:05
Fixed two instances in unixpair(). Other asserts in tcp/udp/unix seem to catch violated assumptions.

One notable exception is when calling close(2). Good discussion of the issues involved can be found here: http://austingroupbugs.net/view.php?id=529

**Comment by sustrik** [comment] 2015-08-04 21:13
tcp/udp/unix libraries now retuen ENOMEM in case of allocation failure.

The remaining functions that can fail because of allocation failure are: go(), chmake() and chrecv() and choose{}.

**Comment by sustrik** [comment] 2015-08-05 05:50
chmake() now returns NULL of allocation failure. Tricky ones remain: go(), chr() and choose{}.

**Comment by sustrik** [comment] 2015-08-08 13:25
Fixed by introducing a way to preallocate the stacks:
http://libmill.org/documentation.html#memory

**Comment by trapzero** [comment] 2015-08-10 15:45
The memory updates look pretty good.  Nice work.

In reading through the code, I'm still concerned about the asserts being in there since they call abort(), and bring the whole process down.  Similar reasoning as before.  The library isn't as important as the main process and shouldn't bring everything down if it finds itself in a bad state.

**Comment by sustrik** [comment] 2015-08-10 15:49
The asserts there test assumptions. If the condition fails it means that the library exhibits undefined behaviour. It may well be overwriting memory. What would you do in such case?

**Comment by trapzero** [comment] 2015-08-10 17:40
I would exit the function ASAP and return an error.  I'd probably define a custom ASSERT() function.  When in debug mode, then call assert/abort.  If in release/non-debug, then probably just print to stderr so a developer will know there's a problem.

You're right, it could be memory being corrupted, but it could be an issue w/ the main program and not libmill.  Printing out what the inconsistency is will likely help other developers debug and develop their code.

**Comment by sustrik** [comment] 2015-08-10 18:01
Well, as already noted, my life is too short to spend it debugging undefined behaviour. So no.

Closing the issue.

**Closed by sustrik** 2015-08-10 18:01 UTC

**Comment by sustrik** [comment] 2015-08-10 18:09
To put it another way: If you are using a library you have to trust it not to segfault. You also have to trust it not to sigabrt.

**Comment by trapzero** [comment] 2015-08-10 18:32
...which is why a library should *not* have code that calls abort in the first place.  It's not that you have to do any extensive debugging for this; it's just returning an error immediately back to the caller.  This allows the caller to handle the error condition (and possibly other issues) w/o having to rely on a signal handler for the sigabort.
